### PR TITLE
Assignment

### PR DESCRIPTION
**Pull request by adgentinian**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
The code organizes and processes raw data. It creates a main 'data' directory, moves raw data to 'data/raw', and creates subdirectories for different log types in 'data/processed'. It copies relevant log files to their respective subdirectories, removes files containing IP addresses for privacy, and generates an 'inventory.txt' file listing all processed files.

## What did you learn from the changes you have made?
I learned how to organize directories and files and create subdirectories and files with specifications.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
Not at all. I don't yet know how to introduce a different approach.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Everything was a challenge. Especially when trying to understand the logic behind certain commands. For example. $git branch -c NAME, what does that "c" mean? Is C for create? I checked online, and it seems that these variables depend on the context in which they are applied. 
Another issue was setting up Bash properly. I don't know why I still see errors, but I will work on it ASAP.

## How were these changes tested?
Line by line on the Bash terminal within VS.

## A reference to a related issue in your repository (if applicable)
I did the process three or four times. One of my big errors was to "merge" a pull request. One of the tutors "cancelled it" from the dsi GitHub account.

## Checklist
- [ X] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by adgentinian** [comment]
I can't see the autograder...

**Comment by adgentinian** [comment]
Autograder **enabled**!

**Review by anjali-deshpande-hub — CHANGES_REQUESTED** [review]
1. I noticed that assignment.sh file in your 'main' branch has diverged from the version in the forked repository. In a real project setup, the 'main' branch is the stable, deployable version of the project, while 'branches' isolate work for features, bug fixes, or experiments, ensuring main stays clean and reliable. 
Please try to update 'main' so that it doesn't have any of your changes. When this is fixed you will see autograder showing you a table with checkmarks/cross for each question.

2. For Question no. 8, 'cd' command has been used to change directories. It’s generally not advisable to use the cd command in a shell script. Maintaining the same current working directory before and after the script is considered a good practice.

**Comment by adgentinian** [comment]
@anjali-deshpande-hub 

1- I edited and saved the script file from the **main**  (removed an answer line), but I still can't see the autograder.
2- What command should I have used?

**Comment by anjali-deshpande-hub** [comment]
Use option 1 in this message on slack's help channel: https://uoft-dsi-certificates.slack.com/archives/C07VC7M4PTL/p1732596801781119

**Pull request closed without merging**
